// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuInn1LvooDjuzpAhqXAkUeC7k7ET26-A',
    appId: '1:429478821172:web:e436aa7f0f1d9dae6e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    authDomain: 'wafarha-2bf77.firebaseapp.com',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
    measurementId: 'G-J7PBTL7WER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlTTWfxgTBDC7ckX2H2rKpOQo-6enpDKQ',
    appId: '1:429478821172:android:3ff3f0ea7eacce0e6e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-k3iHU_gbzmNnnjnDYawt0boIT8kQerI',
    appId: '1:429478821172:ios:7fbbe73e49c7c2306e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
    iosClientId: '429478821172-mql70stuepd50lpd017sgg2i596rvv2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-k3iHU_gbzmNnnjnDYawt0boIT8kQerI',
    appId: '1:429478821172:ios:c5b70eea3b975dc16e3961',
    messagingSenderId: '429478821172',
    projectId: 'wafarha-2bf77',
    databaseURL: 'https://wafarha-2bf77-default-rtdb.firebaseio.com',
    storageBucket: 'wafarha-2bf77.appspot.com',
    iosClientId: '429478821172-e4d50j4r32pq5e2j2u47ki19k5m17l3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpandaUser.RunnerTests',
  );
}
